### ISSUE TITLE
A few notes... before v1.0

### ISSUE THREAD

**Issue by leeoniya** [jlgrall/domvm-mobx#1]
Hey @jlgrall thanks for transferring the repo :)

> Contrary to advices for normal views, reactive views can be smaller without decreasing the performance after the first render. Simply because while they are not stale, they short-circuit all the work needed during re-rendering (vtree regeneration, diffing and dom reconciliation). So you can make more and smaller views than you would otherwise.

I would probably reword this.

Sub-views (as opposed to sub-templates) incur the overhead of:

1. Instantiating a new vm during initial render and/or mount (and maintaining it in memory)
2. Creating temporary vw() nodes on each redraw of a parent vm

If the sub-views need private state, or are sufficiently heavy **and `diff` is implemented**, then they likely offset the above costs. On the other hand, if the sub-views only generate a few vnodes, then they may not. So the advice against micro-views isn't nullified by `domvm-mobx`. These bindings simply remove the need to manually implement & carefully maintain a `diff`, which is great.

also, since `willUnmount` hooks can return a Promise to prevent a parent from being removed until resolution (outro transitions, etc), they add removal overhead to all ancestors by having to traverse the subtrees prior to actual removal [1].

> `becomeStale`...This new lifecycle hook is called when the observed data has changed. It is responsible for redrawing the vm. Thus by default, all reactive views are setup with a default becomeStale() hook which schedules an async redraw. So if you want to change the default behavior, you can either set it to false to disable it or to your own function to replace the default hook. You are then responsible for scheduling the redraw.

`becameStale` (with an "a") is probably a better name (past tense). semantically it is really similar to `willUpdate` notification hook, except that `willUpdate` cannot short-circuit redraws (it is assumed you do that via `diff` already or return the existing `vm.node` from render). since `diff` is co-opted by this plugin, i guess you need `becameStale` to handle that capability. still feels like some duplication can be avoided. if we give `willUpdate` the ability to short-circuit redraws via a `false` return, maybe we can simply reuse that? we can maybe wrap it and re-fire with and extra `observedData` or `otherData`: `willUpdate(vm, data, otherData)`.

> // TODO: vm.config() was renamed vm.cfg() in domvm v3.4.7, but domvm.config() was not renamed, so we wait for stabilization.

they weren't renamed, i just added the shorter aliases:

https://github.com/domvm/domvm/blob/master/dist/nano/domvm.nano.js#L1512
https://github.com/domvm/domvm/blob/master/dist/nano/domvm.nano.js#L1863

i'm thinking of splitting the demos/playground into its own repo, too.

it would be cool to add a MobX (observables) demo to the https://domvm.github.io/domvm/demos/ alongside Flyd (streams) and Freezer (immutable) state management demos.

[1] https://github.com/domvm/domvm/blob/master/src/view/dom.js#L30

**Comment by leeoniya** [comment]
ping @jlgrall

**Comment by jlgrall** [comment]
Hi, I am back, I will answer this week.

**Comment by leeoniya** [comment]
ping @jlgrall

**Comment by jlgrall** [comment]
> I will answer this week.

I was a bit presumptuous :)  

Thanks for offering to transfer the repo. I am doing this on my free time, so it is not a priority, but I am dedicating time to this project, at least until I can make a release, and then I will keep maintaining it if MobX or domvm introduces any change that breaks it, as I already said.

I will get back to you about the Sub-views overhead and the rewrite of the related text later.

`becomeStale` -> `becameStale`: ok thanks (english is not my native language).

At the origin, `becameStale` is the equivalent of [`componentWillReact`](https://github.com/mobxjs/mobx-preact#componentwillreact-lifecycle-hook) for MobX bindings for other libraries. I did not want to keep the name because domvm doesn't use react names like `shouldComponentUpdate`. So I choose `becomeStale` which comes from the MobX terminology of stale reactions. Now I think its purpose is separate from `willUpdate`, because it reacts only to data managed by MobX, whereas `willUpdate` reacts to data not managed by MobX. And I think there need to be a way to know when an update comes from MobX, ie. from a stale reaction. This is important for debugging (as is said in the link above). Also, I think that the only case where a user would need to change the default `becameStale` behavior would be when the view uses data managed by MobX at the same time as data that are not managed by MobX. And in this case, having a separate `becameStale` probably makes it easier to precisely react to the updates. 

I don't think adding a short-circuit ability to `willUpdate` is worth it, at least it should not be done in the domvm project as that would unnecessarily impact too many people. I could patch the `willUpdate` from domvm-mobx, but for the reasons explain above, I think it is simpler to use `becomeStale`. But I am still open to discussions.

About the rename of `vm.config()` to `vm.cfg()`: ok, i will keep using the default `vm.config()`, and change the comment. (I usually write these comments because if in the future the "old" name were removed, it would be easier to find the origin of the problem and the fix.)

Yeah, it would be cool to add a demo in the playground. I will think about something. Maybe something like the [Complete example](https://github.com/domvm/domvm-mobx#complete-example).

**Comment by leeoniya** [comment]
> and then I will keep maintaining it if MobX or domvm introduces any change that breaks it, as I already said.

i can probably handle updates for any domvm changes, but i don't have any plans currently for changing the API.

i'm okay keeping `becameStale` separate.

i don't think `vm.config()` will be dropped any time soon (it doesnt take up much space in the lib). i added `vm.cfg()` because in app code it may be repeated frequently, so a shorter variant results in smaller bundles.

> Yeah, it would be cool to add a demo in the playground. I will think about something.

👍

**Comment by jlgrall** [comment]
@leeoniya Going back to your comment on the section _What is the ideal size of a reactive view ?_ in the `Readme.md`:

> If the sub-views need private state, or are sufficiently heavy **and `diff` is implemented*, then they likely offset the above costs. On the other hand, if the sub-views only generate a few vnodes, then they may not. So the advice against micro-views isn't nullified by `domvm-mobx`. These bindings simply remove the need to manually implement & carefully maintain a diff, which is great.

Ok, so maybe I should replace the whole section _What is the ideal size of a reactive view ?_ with a link to https://github.com/domvm/domvm#sub-views-vs-sub-templates

I don't know if there is actually any useful advice that I could give to help people on this matter.

From my own experience with converting a project from domvm to domvm-MobX, I see that it makes the first render slower, and that the partial renders with MobX are sometimes slower, sometimes faster than a full render with only domvm. But I got almost completely rid of the redraw logic which did cause problems following tricky sequences of events, which is great.

**Comment by leeoniya** [comment]
> From my own experience with converting a project from domvm to domvm-MobX, I see that it makes the first render slower, and that the partial renders with MobX are sometimes slower, sometimes faster than a full render with only domvm.

i think if the perf situation is sufficiently nuanced, then it's probably worth keeping any perf related claims out of the readme.

> Ok, so maybe I should replace the whole section _What is the ideal size of a reactive view ?_ with a link to https://github.com/domvm/domvm#sub-views-vs-sub-templates

sure, if you feel the need to repeat it at all.

> But I got almost completely rid of the redraw logic which did cause problems following tricky sequences of events, which is great.

👍

you can word it however you like, i just want to make sure *you* yourself understand the tradeoffs when writing the docs to avoid blanket claims. it's fair to say that adding a good state management solution (streams, immutable stores, reactive observables) to domvm will reduce some amount of imperative redraw code from views. in the mobx case [with domvm-mobx] it also handles creating and maintaining view `diff` code.

**Comment by jlgrall** [comment]
Ok, thanks for your answers, it is really great and they are useful. I ended up rewriting a large part of the `Readme.md`, simplifying and removing unneeded parts.

**I am going to make a first release soon**

I finished integrating it into my project, so I am confident in it. I am ready to make a release. But before that, I still need to test with different versions of MobX.

I am not sure I will add some testing yet. There is now a playground demo which covers a large part of domvm-MobX. Even the issue #2 (Redraw bug with domvm's drainQueue()) can be seen with it if it happens again. So I will probably wait until the first bug is reported.

A test suite could make it easier to find breaking changes in domvm or MobX, though...
